const translations={
tr:{navHome:"Ana Sayfa",navProducts:"Ürünler",navSystems:"Sistemler",navAbout:"Biz",navContact:"İletişim",eyebrow:"METAL ASMA TAVAN SİSTEMLERİ",heroTitle:"Modern mekanlar için<br><strong>üstün tavan çözümleri.</strong>",heroText:"Dekoratif, dayanıklı ve kullanıma özel metal tavan sistemleri.",discover:"Ürünleri Keşfet",productEyebrow:"ÜRÜN GRUPLARI",productTitle:"Tavan sistemlerinde<br>fonksiyon ve estetik.",p1:"Clip-in Tavanlar",p1d:"Gizli taşıyıcılı, temiz ve modern görünüm.",p2:"Lay-in Tavanlar",p2d:"Kolay montaj ve bakım avantajı sağlayan sistemler.",p3:"Lay-on Tavanlar",p3d:"Ekonomik ve hızlı uygulanabilen tavan çözümü.",p4:"Doğrusal Tavanlar",p4d:"Mimari çizgileri güçlendiren lineer tasarımlar.",p5:"Petek Tavanlar",p5d:"Açık tavan etkisi ve güçlü mimari karakter.",p6:"Panel 85",p6d:"Geniş açıklıklarda modern ve dengeli görünüm.",systemTitle:"Projeye uygun taşıyıcı çözümler.",aboutEyebrow:"EGE MAT",aboutTitle:"Mimariye değer katan tavanlar.",aboutText:"Projelerin ihtiyaçlarına göre metal asma tavan sistemleri sunuyoruz. Estetik, dayanıklılık, hızlı uygulama ve sürdürülebilir çözümleri bir araya getiriyoruz.",contactUs:"Bizimle iletişime geç →",contactTitle:"Projenizi birlikte<br>konuşalım.",footer:"Metal Asma Tavan Sistemleri"},
en:{navHome:"Home",navProducts:"Products",navSystems:"Systems",navAbout:"About",navContact:"Contact",eyebrow:"METAL SUSPENDED CEILING SYSTEMS",heroTitle:"Superior ceiling<br><strong>solutions for modern spaces.</strong>",heroText:"Decorative, durable and project-specific metal ceiling systems.",discover:"Explore Products",productEyebrow:"PRODUCT GROUPS",productTitle:"Function and aesthetics<br>in ceiling systems.",p1:"Clip-in Ceilings",p1d:"Clean modern look with concealed grid.",p2:"Lay-in Ceilings",p2d:"Easy installation and maintenance.",p3:"Lay-on Ceilings",p3d:"Economical and fast ceiling solution.",p4:"Linear Ceilings",p4d:"Linear designs that strengthen architecture.",p5:"Cell Ceilings",p5d:"Open ceiling effect with strong character.",p6:"Panel 85",p6d:"Modern balanced look for wide spans.",systemTitle:"Carrier solutions for every project.",aboutEyebrow:"EGE MAT",aboutTitle:"Ceilings that add value to architecture.",aboutText:"We provide metal suspended ceiling systems tailored to project requirements, combining aesthetics, durability and efficient installation.",contactUs:"Contact us →",contactTitle:"Let's discuss<br>your project.",footer:"Metal Suspended Ceiling Systems"},
es:{navHome:"Inicio",navProducts:"Productos",navSystems:"Sistemas",navAbout:"Nosotros",navContact:"Contacto",eyebrow:"SISTEMAS DE TECHOS METÁLICOS",heroTitle:"Soluciones de techo<br><strong>para espacios modernos.</strong>",heroText:"Sistemas de techo metálico decorativos, duraderos y personalizados.",discover:"Ver productos",productEyebrow:"GRUPOS DE PRODUCTOS",productTitle:"Función y estética<br>en sistemas de techo.",p1:"Techos Clip-in",p1d:"Aspecto moderno y limpio con estructura oculta.",p2:"Techos Lay-in",p2d:"Fácil instalación y mantenimiento.",p3:"Techos Lay-on",p3d:"Solución económica y rápida.",p4:"Techos Lineales",p4d:"Diseños lineales que refuerzan la arquitectura.",p5:"Techos Celulares",p5d:"Efecto de techo abierto y fuerte carácter.",p6:"Panel 85",p6d:"Aspecto moderno para grandes luces.",systemTitle:"Soluciones de soporte para cada proyecto.",aboutEyebrow:"EGE MAT",aboutTitle:"Techos que aportan valor a la arquitectura.",aboutText:"Ofrecemos sistemas de techos metálicos adaptados a cada proyecto, combinando estética, durabilidad e instalación eficiente.",contactUs:"Contáctenos →",contactTitle:"Hablemos de<br>su proyecto.",footer:"Sistemas de Techos Metálicos"}};

function setLanguage(lang){
 const t=translations[lang]||translations.tr;
 document.documentElement.lang=lang;
 document.querySelectorAll("[data-i18n]").forEach(el=>{if(t[el.dataset.i18n]!==undefined)el.innerHTML=t[el.dataset.i18n]});
 document.querySelectorAll("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));
 localStorage.setItem("egemat-lang",lang);
}
document.addEventListener("DOMContentLoaded",()=>{
 document.getElementById("year").textContent=new Date().getFullYear();
 document.querySelectorAll("[data-lang]").forEach(b=>b.addEventListener("click",()=>setLanguage(b.dataset.lang)));
 const toggle=document.querySelector(".menu-toggle"),menu=document.querySelector(".menu");
 toggle.addEventListener("click",()=>menu.classList.toggle("open"));
 document.querySelectorAll(".menu a").forEach(a=>a.addEventListener("click",()=>menu.classList.remove("open")));
 setLanguage(localStorage.getItem("egemat-lang")||"tr");
});
